# -*- coding: utf-8 -*-
"""prediksi_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vBlaUf252pdbmWIHwESvTgj_m2XW3A4
"""

import streamlit as st
import pandas as pd
import joblib

st.title("🌾 Prediksi Produksi Padi – Growth Projection")

# 1. Upload file Excel
uploaded_file = st.file_uploader("Unggah data historis (Excel)", type=["xlsx"])

if uploaded_file is not None:
    df_pred = pd.read_excel(uploaded_file)
    st.write("✅ Data berhasil dimuat:")
    st.dataframe(df_pred.head())

    # 2. Load model
    model = joblib.load("model_rf.pkl")

    # 3. Tahun terakhir
    last_year = df_pred["Tahun"].max()
    st.write(f"Data terakhir tersedia: **{last_year}**")

    if st.button("🔮 Proyeksikan Tahun Berikutnya"):
        # hitung growth rata-rata
        growth = (
            df_pred[df_pred["Tahun"].between(last_year-2, last_year)]
            .groupby("Kecamatan")[["Luas Sawah","Luas Tanam","Luas Panen","Produktivitas Padi"]]
            .pct_change()
            .groupby(df_pred["Kecamatan"]).mean()
        )

        df_last = df_pred[df_pred["Tahun"] == last_year].set_index("Kecamatan")
        df_proj = df_last.copy()
        df_proj[["Luas Sawah","Luas Tanam","Luas Panen","Produktivitas Padi"]] *= (1 + growth)

        df_proj["Tahun"] = last_year + 1
        df_proj = df_proj.reset_index()

        # fitur turunan
        df_proj["Rasio_Tanam"] = df_proj["Luas Panen"] / (df_proj["Luas Tanam"]+1e-9)
        df_proj["Intensitas_Sawah"] = df_proj["Luas Tanam"] / (df_proj["Luas Sawah"]+1e-9)
        df_proj["Prod_Ekspektasi"] = df_proj["Luas Panen"] * df_proj["Produktivitas Padi"]

        # prediksi
        X_proj = df_proj.drop(columns=["Tahun","Produksi"], errors="ignore")
        y_pred_proj = model.predict(X_proj)
        df_proj["Prediksi Produksi"] = y_pred_proj.round(0)

        st.success(f"✅ Prediksi Produksi Padi Tahun {last_year+1}")
        st.dataframe(df_proj[["Kecamatan","Tahun","Prediksi Produksi"]])
        st.write("📊 Total Produksi:", int(df_proj["Prediksi Produksi"].sum()))
else:
    st.info("⬆️ Silakan unggah file Excel untuk mulai prediksi.")